# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

name: blendnerf
channels:
  - pytorch
  - nvidia
dependencies:
  - python =3.8
  - pip
  - numpy =1.23.5
  - click 
  - pillow 
  - scipy
  - pytorch =1.11.0
  - torchvision =0.12.0
  - cudatoolkit =11.3
  - requests =2.26.0
  - tqdm =4.62.2
  - ninja =1.10.2
  - matplotlib =3.4.2
  - imageio =2.9.0
  - pyembree

  - pip:
    - imgui ==1.3.0
    - glfw ==2.2.0
    - pyopengl ==3.1.5
    - imageio-ffmpeg ==0.4.3
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - munch
    - trimesh
    - plyfile
    - scikit-image ==0.19.3
    - plotly
    - IPython
    - scikit-video
    - opencv-python
    - rtree
    - lpips
    - gdown
